import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import Header from "./components/Header";

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Risk Ray</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full min-h-screen bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Header />
        <div className="container flex min-w-full flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h2 className="text-4xl font-bold text-white">Contact us</h2>
        </div>
      </main>
    </>
  );
};

export default Home;
